import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { useDispatch, useSelector } from "react-redux/es/exports";
import { AppDispatch, RootState } from "@/store/store";
import { useEffect, useRef } from "react";
import { fetchUsers, increment } from "@/store/slices/userSlice";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const userRef = useRef(false);
  const { entities, loading, value } = useSelector(
    (state: RootState) => state.user ?? null
  );
  const dispatch = useDispatch<AppDispatch>();

  useEffect(() => {
    if (userRef.current === false) {
      dispatch(fetchUsers());
    }

    return () => {
      userRef.current = true;
    };
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          {loading ? (
            <h1>Loading...</h1>
          ) : (
            entities?.map((user: any) => <h3 key={user.id}>{user.name}</h3>)
          )}

          <button onClick={() => dispatch(increment())}>Click on me</button>
          {value}
        </div>
      </main>
    </>
  );
}
